config/routes.rb
Rails.application.routes.draw do
  resources :moderators
  root 'users#index'
  get '/users/sorting_hat' => 'users#sorting_hat'
  get '/moderator-email' => 'moderators#moderator_email'
  resources :users do
    member do
      get :confirm_email
    end
  end
  default_url_options :host => 'localhost:3000'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/moderator.rb
class Moderator < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/moderators_controller.rb
class ModeratorsController < ApplicationController
  before_action :set_moderator, only: [:show, :edit, :update, :destroy]

  # GET /moderators
  # GET /moderators.json
  def index
    @moderators = Moderator.all
  end

  # GET /moderators/1
  # GET /moderators/1.json
  def show
  end

  # GET /moderators/new
  def new
    @moderator = Moderator.new
  end

  # GET /moderators/1/edit
  def edit
  end

  # POST /moderators
  # POST /moderators.json
  def create
    @moderator = Moderator.new(moderator_params)

    respond_to do |format|
      if @moderator.save
        format.html { redirect_to @moderator, notice: 'Moderator was successfully created.' }
        format.json { render :show, status: :created, location: @moderator }
      else
        format.html { render :new }
        format.json { render json: @moderator.errors, status: :unprocessable_entity }
      end
    end
  end

  def moderator_email
    @secret_list = User.all
    @moderator = Moderator.first

    UserMailer.with(email: @moderator.email, name: @moderator.name, secret_list: @secret_list).moderator.deliver_now
  end

  # PATCH/PUT /moderators/1
  # PATCH/PUT /moderators/1.json
  def update
    respond_to do |format|
      if @moderator.update(moderator_params)
        format.html { redirect_to @moderator, notice: 'Moderator was successfully updated.' }
        format.json { render :show, status: :ok, location: @moderator }
      else
        format.html { render :edit }
        format.json { render json: @moderator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moderators/1
  # DELETE /moderators/1.json
  def destroy
    @moderator.destroy
    respond_to do |format|
      format.html { redirect_to moderators_url, notice: 'Moderator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_moderator
      @moderator = Moderator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moderator_params
      params.require(:moderator).permit(:name, :email)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def confirm_email
    @user = User.find_by_confirm_token(params[:id])
    if @user
      user.email_activate
      flash[:success] = "Welcome to the Book App! Your email has been confirmed.
      Please sign in to continue."
      redirect_to root_url
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to root_url
    end
  end

  def sorting_hat
    @users = User.all
    @sorting = @users.shuffle
    @sorting.each_with_index do |santa,index|
      if !@sorting[index+1].nil?
        santa.update(secret: @sorting[index+1].name)
      else
        santa.update(secret: @sorting[0].name)
      end
    end

    @sorting.each do |u|
      UserMailer.with(email: u.email, name: u.name, secret: u.secret).secret_email.deliver_now
    end
    redirect_to root_url
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :secret, :wishlist)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moderators_helper.rb
module ModeratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecretSanta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
     <%= javascript_include_tag 'snowstorm-min', 'data-turbolinks-track': 'reload' %>
     <%= javascript_include_tag 'snowstorm', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/moderators/_form.html.erb
<%= form_with(model: moderator, local: true) do |form| %>
  <% if moderator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(moderator.errors.count, "error") %> prohibited this moderator from being saved:</h2>

      <ul>
      <% moderator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/moderators/edit.html.erb
<h1>Editing Moderator</h1>

<%= render 'form', moderator: @moderator %>

<%= link_to 'Show', @moderator %> |
<%= link_to 'Back', moderators_path %>

app/views/moderators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moderators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moderators.each do |moderator| %>
      <tr>
        <td><%= moderator.name %></td>
        <td><%= moderator.email %></td>
        <td><%= link_to 'Show', moderator %></td>
        <td><%= link_to 'Edit', edit_moderator_path(moderator) %></td>
        <td><%= link_to 'Destroy', moderator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         <td><%= link_to 'Send e-mail to moderator', '/moderator-email' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Moderator', new_moderator_path %>

app/views/moderators/moderator_email.html.erb
<h1>E-mail has been sent!</h1>

app/views/moderators/new.html.erb
<h1>New Moderator</h1>

<%= render 'form', moderator: @moderator %>

<%= link_to 'Back', moderators_path %>

app/views/moderators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @moderator.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @moderator.email %>
</p>

<%= link_to 'Edit', edit_moderator_path(@moderator) %> |
<%= link_to 'Back', moderators_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

   <div class="field">
    <%= form.label :wishlist %>
    <%= form.text_field :wishlist %>
  </div>
  <br />
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<section id="banner" class="major">
  <div class="inner">
    <header class="major">
      <h1>Hi, Wyncode</h1>
    </header>
    <div class="content">
      <p>Let's play a Secret Santa.</p>
      <ul class="actions">
       <li><%= link_to 'Add a new participant', new_user_path, class: "button next scrolly" %></li>
      </ul>
    </div>
  </div>
</section>

<p id="notice"><%= notice %></p>

<h1>Participants @ Wyncode C-30</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
       <th>Wish-List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.wishlist %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Destroy', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', users_path %>

app/views/users/sorting_hat.html.erb
<h1>Vamos a jugar Secret Santa</h1>
<ul>
<% @sorting.each do |user| %>
<li><%= user.name + " => " +user.secret %> </li>
<% end %>
</ul>
<hr />